#   _ __   ___  ___  __ _ _ __   __ _
#  | '_ \ / _ \/ __|/ _` | '_ \ / _` |
#  | | | | (_) \__ \ (_| | | | | (_| |
#  |_| |_|\___/|___/\__,_|_| |_|\__,_|

include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: docker-container.yml

variables:
  DOCKERFILE_DIR: .
  CONTAINER_PLATFORMS: linux/amd64
  REG_REPOSITORY: nosana/nosana-cli

deploy:
  image: node:20.11.1
  stage: deploy
  only:
    - main
  script:
    - sed -i "s/0.0.0/${CI_COMMIT_TAG:1}/" package.json
    - npm ci --omit=dev
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm run publish:public
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG != "latest"
