#   _ __   ___  ___  __ _ _ __   __ _
#  | '_ \ / _ \/ __|/ _` | '_ \ / _` |
#  | | | | (_) \__ \ (_| | | | | (_| |
#  |_| |_|\___/|___/\__,_|_| |_|\__,_|

image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm ci
    - git config --global user.email "dev@nosana.io"
    - git config --global user.name "Nosana"
    - npm publish      